export const incompletedTasks = [
  {
    id: 4,
    title: "Dhuhr Prayer",
    description: "Afternoon prayer - don't miss it!",
    completed: false,
    priority: "high",
    category: "prayer",
    created_at: "2025-10-01T12:30:00.000Z",
  },
  {
    id: 5,
    title: "Islamic History Study",
    description: "Study the life of Prophet Muhammad (PBUH)",
    completed: false,
    priority: "medium",
    category: "study",
    created_at: "2025-10-01T10:00:00.000Z",
  },
  {
    id: 6,
    title: "Family Gathering",
    description: "Organize weekend family dinner",
    completed: false,
    priority: "medium",
    category: "family",
    created_at: "2025-10-01T09:00:00.000Z",
  },
  {
    id: 7,
    title: "Work Project Deadline",
    description: "Complete quarterly report for work",
    completed: false,
    priority: "high",
    category: "work",
    created_at: "2025-10-01T08:00:00.000Z",
  },
  {
    id: 8,
    title: "Evening Dhikr",
    description: "Remember Allah with evening remembrance",
    completed: false,
    priority: "medium",
    category: "prayer",
    created_at: "2025-10-01T18:00:00.000Z",
  },
];
